[package]
name = "librs"
version = "0.1.0"
edition = "2021"

[profile.dev]
panic ="abort"

[profile.release]
panic ="abort"

#[profile.test]
#panic ="abort"

[lib]
crate-type=["staticlib"]

[dependencies]
